package de.teamproject.drunkenslot.engine;

/**
 * SlotImage class that stores the generated data from the SlotMachine.
 * @author Dominik Haacke
 *
 */
public class SlotImage 
{
	private int values[][];
	
	/**
	 * Constructor for the SlotImage.
	 * @param values Values generated by the SlotMachine, for the orientation, top left is (0,0).
	 */
	public SlotImage(int values[][])
	{
		this.values = values;
	}
	
	/**
	 * Get the data from position (x,y) in the values Array
	 * @param x x-Value
	 * @param y y-Value
	 * @return value on position (x,y) if it exists, else return -1;
	 */
	public int get(int x, int y)
	{
		if(x < values.length)
		{
			if(y < values[0].length)
			{
				return values[x][y];
			}
			return -1;
		}
		return -1;
	}
	
	/**
	 * Set the data on position(x,y) in the values array, if x and y are in the range.
	 * @param x
	 * @param y
	 * @param value
	 */
	public void set(int x, int y, int value)
	{
		if(x < values.length)
		{
			if(y < values[0].length)
			{
				values[x][y] = value;
			}
		}
	}
	
	public int getLengthX()
	{
		return values.length;
	}
	
	public int getLengthY()
	{
		return values[0].length;
	}
}